### PR TITLE
Review CLI interface: update appearance, user feedback and workflow

### PR DESCRIPTION
**Pull request by a1ro**
As mentionned in #40, I made some changes to the command line interface.

When running `birdears --cli load demo.toml` with this config,

```
exercise = 'melodic'
chromatic = true
tonic = 'C'
octave = 3
valid_intervals = [1, 5]
```

I get the following output.

---

1. Print the exercise title (**new**) followed by question info:

```

  -->                       Melodic interval recognition
  -->                       ────────────────────────────
           KEY: C major
           (chromatic: True; descending: False)

           Intervals P1  m2  M2  m3  M3  P4  A4  P5  m6  M6  m7  M7  P8
           Scale     C3  C#3 D3  D#3 E3  F3  F#3 G3  G#3 A3  A#3 B3  C4
           Keyboard  z   s   x   d   c   v   g   b   h   n   j   m   ,
           ──────────────────────────────────────────────────────────────

```

2. Play the first question, then show a prompt with available actions (**new**):

```

  -->                          What is the interval?
  -->                          ─────────────────────
  -->                    key- answer   r- repeat   q- quit

```

3. If a valid key is pressed, print response:

```

                                 “Perfect Fourth” (C3─F3)
                          user ✓ “Perfect Fourth” (C3─F3)
                          5 semitones
                          ───────────────────────────────
                                      Correct!

```

4. Play the resolution, then show a second prompt with available actions (**new**):

```

  -->                              Next question
  -->                              ─────────────
  -->                          space- play   q- quit

```

5. If space (or enter) is pressed, loop back to step 1.

---

Notes:
+ A second _Getch() after the "Next question" prompt allows to pause the program and let the user read the response
+ The screen is cleared before each question, which means the same lines get printed over (i.e., the output does not "move")
+ Separators are dim (easier to focus on text)
+ "Correct!" is green, "Wrong" is red

### CODE REVIEW

**Comment by iacchus** [comment]
LOL. I think we have a bug here. I have executed your `.toml` and received only m2 and P4 as aswers.

If `valid_intervals = [1, 5]` and `chromatic = true` the fifth should only be `d5`, `P5` or `A5`.

**Comment by iacchus** [comment]
@a1ro  My mistake, sorry :) `valid_interval` is measured in semitones, in which [1,5] is indeed m2 and P4. Much time without messing with the code, really sorry Antoine.  :)

**Comment by iacchus** [comment]
@a1ro  The only thing I *really* don't like in your PR is the need to play space for the next question; I think it wastes time and is unnecessary.

**Comment by a1ro** [comment]
No worries.

Here's part of my thinking behind this:
- The TUI layout reflects the arrangement of standard piano keys
- The keybindings also reflect this layout (i've been thinking about customizing those)
- While most users will be fine with it, it is not always appropriate for other types of musical instruments or midi controllers they could be practicing with
- This software is mostly about interval recognition which, in my opinion, should not relate to input methods but rather to notes and pitches exclusively
- The CLI currently ticks all those boxes very well (except for the fixed keybindings)

And why I add an extra prompt (press space to continue):
- When the resolution plays after answering, I'm always confused as to where the resolution ends and where the new question begins. A pause between the two helps (but adding a fixed delay would only slow down the exercise)
- After disabling the resolution altogether, I found it easier to concentrate on the actual question
- But then, right after I answer I get a new question which does not give me time to process the answer
- With the extra info added to the response in #47, I except the user to have a look at it, possibly learn from their mistake, then go on with another question when ready
- Finally, adding this extra prompt allowed to print the response and leave it there for as long as needed, then clear the screen for a new question (and prevent the output from scrolling down each time)

With that said, It is perfectly fine for the TUI to be the default interface. Intuitive, plenty of visual feedback and relates to what most people are already used to.

By contrast, the CLI has potential for custom scenarios which could be set with new options.

I hope this makes sense.

**Pull request merged**
